async function ONLINE_COUNTER() {}
async function OFFLINE_COUNTER() {}
async function MEMBERS_COUNTER() {}
async function WELCOME_MESSAGE() {}

module.exports = {
  ONLINE_COUNTER: ONLINE_COUNTER,
  OFFLINE_COUNTER: OFFLINE_COUNTER,
  MEMBERS_COUNTER: MEMBERS_COUNTER,
  WELCOME_MESSAGE: WELCOME_MESSAGE
};
